[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
privy = "priHJ6iTp11dw7nU8QoFZ4msaEMyk6GnBKfvV3rpNE5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
